# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Conor Hagan
subtitle: Portfolio of the Gods
description: > # A bunch of useless description details about how awesome this
              site is or something.

author:
    name: Conor Hagan
    linkedin: http://linkedin.com
    instagram: http://instagram.com


# Site Configuration
baseurl: ""
url: ""
permalink: none

# Build settings
markdown: kramdown
# theme: agency-jekyll-theme

sass:
  style: :compressed

gems:
  - jekyll-feed
  # - github-pages
exclude:
  - Gemfile
  - Gemfile.lock
